# Copyright 2024 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $fullname := include "qubership-prometheus-adapter-operator.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "qubership-prometheus-adapter-operator.fullname" . }}
  labels:
    name: {{ $fullname }}
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/instance: {{ cat $fullname "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    {{- include "qubership-prometheus-adapter-operator.commonLabels" . | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "qubership-prometheus-adapter-operator.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ $fullname }}
        app.kubernetes.io/name: {{ template "qubership-prometheus-adapter-operator.fullname" . }}
        app.kubernetes.io/instance: {{ cat $fullname "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
        {{- include "qubership-prometheus-adapter-operator.commonLabels" . | nindent 8 }}
        {{- if .Values.labels }}
          {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
      {{- if .Values.annotations }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "qubership-prometheus-adapter-operator.fullname" . }}
        command: ["/manager"]
        args:
          - "--enable-leader-election"
        image: {{ template "prometheus-adapter-operator.image" . }}
        imagePullPolicy: IfNotPresent
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      serviceAccountName: {{ template "qubership-prometheus-adapter-operator.fullname" . }}
