name: Integration Tests

on:
  push:
    branches:
      - '**'  # run for all branches
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Set up Kubernetes API server (envtest)
        run: |  
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          export KUBEBUILDER_ASSETS=$(setup-envtest use -i -p path 1.25.0)
          echo "KUBEBUILDER_ASSETS=${KUBEBUILDER_ASSETS}" >> $GITHUB_ENV

      - name: Run integration tests
        run: |
          go test -v ./integration-tests/...